color_aqua = "#745d8a";
color_bg1 = "#251b2e";
color_bg3 = "#42314b";
color_blue = "#926ba2";
color_fg0 = "#d9b0cf";
color_green = "#745d8a";
color_orange = "#b47d95";
color_purple = "#906895";
color_red = "#a56876";
color_yellow = "#c08ea7";

format = "[](fg:${color_orange})$os[](bg:${color_yellow} fg:${color_orange})$directory[](bg:${color_aqua} fg:${color_yellow})$git_branch$git_status[](bg:${color_blue} fg:${color_aqua})$nix_shell[](bg:${color_bg3} fg:${color_blue})$cmd_duration[](fg:${color_bg3}) "

[os]
disabled = false
style = "bg:${color_orange} bold fg:${color_fg0}"
symbols.Ubuntu = " "

[directory]
style = "bold fg:${color_fg0} bg:${color_yellow}"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:${color_aqua}"
format = "[[ $symbol $branch ](bold fg:${color_fg0} bg:${color_aqua})]($style)"

[git_status]
style = "bg:${color_aqua} bold fg:${color_fg0}"
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:${color_bg1}"
format = "[[   $time ](fg:${color_fg0} bg:${color_bg1})]($style)"

[cmd_duration]
format = "[ 󰔛 $duration ]($style)"
disabled = false
style = "bg:${color_bg3} fg:${color_fg0}"
show_notifications = false
min_time_to_notify = 60000

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[  ](bold fg:${color_aqua})"
error_symbol = "[  ](bold fg:${color_red})"

